# Build the ISO
- name: Build ISO
  uses: jasonn3/build-container-installer@main
  id: build
  with:
    arch: x86_64
    image_name: Meme-OS
    image_repo: ghcr.io/m3m3-0s/meme-os
    image_tag: latest
    version: v1
    variant: Kinoite
    iso_name: Meme-OS-latest-v1.iso

# Upload the ISO as an artifact
- name: Upload ISO as artifact
  id: upload
  uses: actions/upload-artifact@v4
  with:
    name: ${{ steps.build.outputs.iso_name }}
    path: |
      ${{ steps.build.outputs.iso_path }}
      ${{ steps.build.outputs.iso_path }}-CHECKSUM
    if-no-files-found: error
    retention-days: 0
    compression-level: 0
